version: '2'

services:

    plex:
        image: linuxserver/plex
        container_name: plex
        volumes:
            - ${PLEX_CONFIG}:/config
            - ${PLEX_MOVIES}:/data/movies
            - ${PLEX_SHOWS}:/data/tvshows
            - ${PLEX_TRANSCODE}:/data/transcode
        network_mode: host
        restart: always
        environment:
            - VERSION=latest
            - TZ=America/Los_Angeles

    nzbget:
        image: linuxserver/nzbget
        container_name: nzbget
        volumes:
            - ${NZBGET_CONFIG}:/config
            - ${NZBGET_DOWNLOADS}:/downloads
        restart: always
        environment:
            - TZ=America/New_York
        ports:
            - 6789:6789
    sonarr:
        image: linuxserver/sonarr
        container_name: sonarr
        depends_on:
            - nzbget
        volumes:
            - ${SONARR_CONFIG}:/config
            - ${NZBGET_DOWNLOADS}:/downloads
            - ${PLEX_SHOWS}:/tv
        environment:
            - TZ=America/New_York
        ports:
            - 8989:8989
    radarr:
        image: linuxserver/radarr
        container_name: radarr
        depends_on:
            - nzbget
        volumes:
            - ${RADARR_CONFIG}:/config
            - ${NZBGET_DOWNLOADS}:/downloads
            - ${PLEX_MOVIES}:/movies
        environment:
            - TZ=America/New_York
        ports:
            - 7878:7878
    overseerr:
        image: sctx/overseerr:latest
        container_name: overseerr
        environment:
            - LOG_LEVEL=info
            - TZ=America/New_York
        ports:
            - 5055:5055
        volumes:
            - ${OVERSEERR_CONFIG}:/app/config
        restart: unless-stopped
    watchtower:
        image: v2tec/watchtower
        container_name: watchtower
        restart: always
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock