version: "2"

services:
  plex:
    image: linuxserver/plex
    container_name: plex
    volumes:
      - ./config/plex/config:/config
      - ./data/plex/Movies:/data/movies
      - ./data/plex/Shows:/data/tvshows
      - ./data/plex/transcode:/data/transcode
    network_mode: host
    restart: always
    environment:
      - VERSION=latest
      - TZ=America/Los_Angeles

  transmission:
    image: haugene/transmission-openvpn:latest
    container_name: transmission
    restart: always
    ports:
      - "9091:9091"
    # https://haugene.github.io/docker-transmission-openvpn/config-options/
    environment:
      - OPENVPN_PROVIDER=PROTONVPN
      # Fill the following
      - OPENVPN_CONFIG=
      - OPENVPN_USERNAME=
      - OPENVPN_PASSWORD=
      - WEBPROXY_ENABLED=false
      - LOCAL_NETWORK=192.168.0.0/16
      - TRANSMISSION_WEB_UI=flood-for-transmission
    volumes:
      - /media/downloads:/data
      - /etc/localtime:/etc/localtime:ro
    cap_add:
      - NET_ADMIN

  prowlarr:
    image: linuxserver/prowlarr:develop
    container_name: prowlarr
    restart: always
    ports:
      - "9696:9696"
    cap_add:
      - NET_ADMIN
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /media/prowlarr:/config
      - /media/downloads/watch:/downloads

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    depends_on:
      - nzbget
    volumes:
      - ./config/sonarr/config:/config
      - ./data/nzbget/downloads:/downloads
      - ./data/plex/Shows:/tv
    environment:
      - TZ=America/New_York
    ports:
      - 8989:8989

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    depends_on:
      - nzbget
    volumes:
      - ./config/radarr/config:/config
      - ./data/nzbget/downloads:/downloads
      - ./data/plex/Movies:/movies
    environment:
      - TZ=America/New_York
    ports:
      - 7878:7878

  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    environment:
      - LOG_LEVEL=info
      - TZ=America/New_York
    ports:
      - 5055:5055
    volumes:
      - ./config/overseerr/config:/app/config
    restart: unless-stopped

  watchtower:
    image: v2tec/watchtower
    container_name: watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
