version: "2"

services:
  # plex
  plex:
    image: linuxserver/plex
    container_name: plex
    volumes:
      - ./config/plex/config:/config
      - ./data/plex/Movies:/data/movies
      - ./data/plex/Shows:/data/tvshows
      - ./data/plex/transcode:/data/transcode
    network_mode: host
    restart: always
    environment:
      - VERSION=latest
      - TZ=America/Los_Angeles

  # prowlarr handles setting torrent indexers for radarr and sonarr
  prowlarr:
    image: linuxserver/prowlarr:develop
    container_name: prowlarr
    restart: always
    ports:
      - "9696:9696"
    cap_add:
      - NET_ADMIN
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /media/prowlarr:/config
      - /media/downloads/watch:/downloads

  # web gui for radarr/sonarr
  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    environment:
      - LOG_LEVEL=info
      - TZ=America/New_York
    ports:
      - 5055:5055
    volumes:
      - ./config/overseerr/config:/app/config
    restart: unless-stopped

  # tv show download orchestrator
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    volumes:
      - ./config/sonarr/config:/config
      - ./data/transmission/downloads:/downloads
      - ./data/plex/Shows:/tv
    environment:
      - TZ=America/New_York
    ports:
      - 8989:8989

  # movies download orchestrator
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    volumes:
      - ./config/radarr/config:/config
      - ./data/transmission/downloads:/downloads
      - ./data/plex/Movies:/movies
    environment:
      - TZ=America/New_York
    ports:
      - 7878:7878
 
  # torrent client
  transmission:
    image: haugene/transmission-openvpn:latest
    container_name: transmission
    restart: always
    ports:
      - "9091:9091"
    # https://haugene.github.io/docker-transmission-openvpn/config-options/
    environment:
      - OPENVPN_CONFIG=ch.protonvpn.udp # Switzerland
      - OPENVPN_PROVIDER=PROTONVPN
      - DISABLE_PORT_FORWARDER=false
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - WEBPROXY_ENABLED=false
      - LOCAL_NETWORK=192.168.0.0/16
      - TRANSMISSION_WEB_UI=flood-for-transmission
    # Contains OPENVPN_USERNAME, OPENVPN_PASSWORD
    # See here: https://account.protonvpn.com/account
    env_file: "openvpn-credentials.env"
    volumes:
      - ./data/transmission/downloads:/data
      - /etc/localtime:/etc/localtime:ro
    cap_add:
      - NET_ADMIN

  # image updater
  watchtower:
    image: v2tec/watchtower
    container_name: watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
